
POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento 4",
  "details": null,
  "maximumAttendees": 20
}

###

POST http://localhost:3333/events/11f87d83-73cd-4e32-92de-d9198b3cfde9/attendees
Content-Type: application/json

{
  "name": "JohnDoe",
  "email": "jhondoea@gmail.com"
}

###

GET  http://localhost:3333/events/11f87d83-73cd-4e32-92de-d9198b3cfde9


###

GET  http://localhost:3333/attendees/5/badge

###
GET  http://localhost:3333/attendees/5/check-in

###
GET  http://localhost:3333/events/11f87d83-73cd-4e32-92de-d9198b3cfde9/attendees